module.exports = {
  User: require('./User.model'),
  Artist: require('./Artist.model'),
  Album: require('./Album.model'),
  Song: require('./Song.model'),
  Playlist: require('./Playlist.model'),
  Room: require('./Room.model'),
  Vote: require('./Vote.model'),
  Message: require('./Message.model'),
  Notification: require('./Notification.model'),
  FriendRequest: require('./FriendRequest.model'),
  Wallet: require('./Wallet.model'),
  Transaction: require('./Transaction.model'),
  Tip: require('./Tip.model'),
  Subscription: require('./Subscription.model'),
  Report: require('./Report.model'),
  Session: require('./Session.model'),
  Analytics: require('./Analytics.model'),
  AuditLog: require('./AuditLog.model'),
  Conversation: require('./Conversation.model'),
  DirectMessage: require('./DirectMessage.model'),
  PrivacySettings: require('./PrivacySettings.model'),
}
